# Generated by Django 3.0.6 on 2020-05-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_animal', models.CharField(choices=[('beavis.zen', 'beavis.zen'), ('blowfish', 'blowfish'), ('bong', 'bong'), ('bud-frogs', 'bud-frogs'), ('bunny', 'bunny'), ('cheese', 'cheese'), ('cower', 'cower'), ('daemon', 'daemon'), ('default', 'default'), ('dragon', 'dragon'), ('dragon-and-cow', 'dragon-and-cow'), ('elephant', 'elephant'), ('elephant-in-snake', 'elephant-in-snake'), ('eyes', 'eyes'), ('flaming-sheep', 'flaming-sheep'), ('ghostbusters', 'ghostbusters'), ('head-in', 'head-in'), ('hellokitty', 'hellokitty'), ('kiss', 'kiss'), ('kitty', 'kitty'), ('koala', 'koala'), ('kosh', 'kosh'), ('luke-koala', 'luke-koala'), ('meow', 'meow'), ('milk', 'milk'), ('moofasa', 'moofasa'), ('moose', 'moose'), ('mutilated', 'mutilated'), ('ren', 'ren'), ('satanic', 'satanic'), ('sheep', 'sheep'), ('skeleton', 'skeleton'), ('small', 'small'), ('sodomized', 'sodomized'), ('stegosaurus', 'stegosaurus'), ('stimpy', 'stimpy'), ('supermilker', 'supermilker'), ('surgery', 'surgery'), ('telebears', 'telebears'), ('three-eyes', 'three-eyes'), ('turkey', 'turkey'), ('turtle', 'turtle'), ('tux', 'tux'), ('udder', 'udder'), ('vader', 'vader'), ('vader-koala', 'vader-koala'), ('www', 'www')], max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('img', models.TextField()),
            ],
        ),
    ]
