# Generated by Django 3.0.6 on 2020-05-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_animal', models.CharField(choices=[('==', '=='), ('\\', '\\'), ('\\', '\\'), ('^__^', '^__^'), ('(oo)\\_______', '(oo)\\_______'), ('(__)\\', '(__)\\'), (')\\/\\', ')\\/\\'), ('||----w', '||----w'), ('|', '|'), ('||', '||'), ('||', '||')], max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('img', models.TextField()),
            ],
        ),
    ]
